version: '3'
services:
  web:
    image: node:8.6
    # command: bash -c "npm install && npm run start"
    working_dir: /usr/src/app
    tty: true
    ports:
      - '8080:3000'
    volumes:
      - .:/usr/src/app
